export const productsList = [
    { 
        id: "1" , 
        nombre: "Apple iPad Wi-fi 64 Gb (9ª Generación)",              
        marca: "Apple", 
        stock: 25, 
        cantidad : 1,
        precio: 700,  
        categoria:"Tablet", 
        img: "https://i.ibb.co/6g6Cxfm/ipad.jpg",
        imgs:{
            img2:"https://i.ibb.co/NKkC8jr/ipad-img2.jpg",
            img3:"https://i.ibb.co/crxpLsf/ipad-img3.jpg",
            img4:"https://i.ibb.co/8M7nN4L/ipad-img4.jpg",
              
        },
        description:"Lleno de potencia, muy fácil de usar y versátil. El nuevo iPad viene con una espectacular pantalla Retina de 10.2 pulgadas, el potente chip A13 Bionic y una cámara frontal ultra gran angular con Encuadre Centrado. Además, es compatible con el Apple Pencil y el Smart Keyboard.1 Con el iPad, harás de todo como si nada. Y por menos de lo que imaginas."
    },
    { 
        id: "2" , 
        nombre: `Macbook Pro 16.2" M1 Pro 512GB SSD 16GB RAM Gris Espacial`,       
        marca: "Apple", 
        stock: 30, 
        cantidad : 1, 
        precio: 1200, 
        categoria:"Laptop", 
        img: "https://i.ibb.co/k4mspbL/apple-macbook-pro.jpg",
        imgs:{
            img2:"https://i.ibb.co/8Mx9kLD/apple-macbook-pro-img2.webp",
            img3:"https://i.ibb.co/7pybcLY/apple-macbook-pro-img3.webp",
            img4:"https://i.ibb.co/F6N6P9W/apple-macbook-pro-img4.webp",
        },
        description:"La nueva MacBook Pro viene en un modelo de 14 pulgadas con chip M1 Pro. Todas las configuraciones ofrecen un nivel de rendimiento sin precedentes. Así, podrás trabajar con millones de polígonos en Cinema 4D, editar hasta siete secuencias de video ProRes 8K en Final Cut Pro o hacer correcciones de color en HDR de videos ProRes 4444 8K, sin necesidad de un estudio de edición.",
    },
    { 
        id: "3" , 
        nombre: "Iphone 13 Pro Max", 
        marca: "Apple", 
        stock: 40, 
        cantidad : 1, 
        precio: 999,  
        categoria:"Celular", 
        img: "https://i.ibb.co/y0hVXSg/iphone-13-pro-max-gold-select.png",
        imgs:{
            img2:"https://i.ibb.co/f21drSD/iphone-13-pro-max-gold-img2.webp",
            img3:"https://i.ibb.co/23mfH19/iphone-13-pro-max-gold-img3.webp",
            img4:"https://i.ibb.co/G5ztbb3/iphone-13-pro-max-gold-img4.webp",
        },
        description:"Los iPhone 13 Pro tampoco rompen con el diseño, tal y como se esperaba, preservando los bordes en ángulo de 90 grados. Tienen resistencia IP68 y se mantiene el mate del cristal, en contraste con el módulo. Las pantallas son de 6,1 y la tasa de refresco a 120 Hz, algo que hasta ahora sólo habíamos visto en los iPad Pro (hablando de Apple). Viene con el ajuste ProMotion, para que la tasa de refresco se adecúe al uso y así poder gestionar mejor el consumo energético, y junto a ello el notch sufre también cierta reducción, como en el caso de los iPhone 13 y iPhone 13 mini.",
    },
    { 
        id: "4" , 
        nombre: "Iphone 13",         
        marca: "Apple", 
        stock: 70, 
        cantidad : 1, 
        precio: 800,  
        categoria:"Celular", 
        img: "https://i.ibb.co/Ssy8T5k/iphone-13.png",
        imgs:{
            img2:"https://i.ibb.co/0Xsct7F/iphone-13-img2.webp",
            img3:"https://i.ibb.co/KK2DC84/iphone-13-img3.webp",
            img4:"https://i.ibb.co/FhS6g1N/iphone-13-img4.webp",
        },
        description:`Este equipo te permite tener unas fotografías de otro nivel.
        Con cámaras traseras, es el Smartphone que necesitas para que tus fotografías lleguen a un siguiente nivel. Hemos mejorado las funciones y ahora podrás disfrutar al tomar fotos con bajo nivel de luz el innovador lente de 12+12MPx
        Excelente opción de compra para mantenerte siempre conectado con las mejores funciones del mercado.
        Celular completamente funcional que tiene todo lo que necesitas.`,
    },
    { 
        id: "5" , 
        nombre: "Macbook Air '13'",  
        marca: "Apple", 
        stock: 10, 
        cantidad : 1, 
        precio: 1150, 
        categoria:"Laptop", 
        img: "https://i.ibb.co/gr9yNk7/mack-air-13.webp",
        imgs:{
            img2:"https://i.ibb.co/Hdn923w/mack-air-13-img2.jpg",
            img3:"https://i.ibb.co/YWjqYrM/mack-air-13-img3.jpg",
            img4:"https://i.ibb.co/RYkW6HK/mack-air-13-img4.jpg",
        },
        description:"Diseño moderno y compacto con una pantalla LED IPS de 13' con resolución 2K. Almacenamiento de 256 GB. Incluye adaptador de corriente y cable de alimentación",
    },
    { 
        id: "6" , 
        nombre: "Audífonos APPLE AirPods Wireless Charging 2nd Generation",           
        marca: "Apple", 
        stock: 55, 
        cantidad : 1, 
        precio: 500,  
        categoria:"Audifonos", 
        img: "https://i.ibb.co/JjBmx8y/airpods.webp",
        imgs:{
            img2:"https://i.ibb.co/RYtqnQJ/airpods-img2.jpg",
            img3:"https://i.ibb.co/M5hCMb9/airpods-img3.jpg",
            img4:"https://i.ibb.co/HChxHL9/airpods-img4.jpg",
        },
        description:"Los audífonos de APPLE como siempre con mejores experiencias al escuchar música o contestar llamadas mientras se realizan otras actividades.",
    },
    { 
        id: "7" , 
        nombre: `iPad Pro 11" 3ra Generación con Chip M1 - 128GB - Gris Espacial`, 
        marca: "Apple", 
        stock: 45, 
        cantidad:1, 
        precio: 1000, 
        categoria: "Tablet", 
        img: "https://i.ibb.co/BVsdZQy/ipad-pro-11-3era-g.webp",
        imgs:{
            img2:"https://i.ibb.co/5jwJ955/ipad-pro-11-3era-g-img2.webp",
            img3:"https://i.ibb.co/sWt72c1/ipad-pro-11-3era-g-img3.webp",
            img4:"https://i.ibb.co/phpXfnD/ipad-pro-11-3era-g-img4.webp",
        },
        description:"El iPad en su máxima expresión. Un rendimiento fuera de serie con el chip M1, una espectacular pantalla Liquid Retina XDR de 12,9 pulgadas y conexión inalámbrica ultrarrápida.",
    },
    { 
        id: "8" , 
        nombre: "Apple Watch Series 7 GPS 45mm Negro",        
        marca: "Apple", 
        stock: 85, 
        cantidad:1, 
        precio: 800,  
        categoria: "Reloj", 
        img: "https://i.ibb.co/HC5g8nh/apple-watch-series-7.webp",
        imgs:{
            img2:"https://i.ibb.co/mNMXX7h/apple-watch-series-7-img2.webp",
            img3:"https://i.ibb.co/pQSM8M7/apple-watch-series-7-img3.webp",
            img4:"https://i.ibb.co/TbBxjPW/apple-watch-series-7-img4.webp",
        },
        description:"¡El Apple Watch más resistente! Su diseño es a prueba de golpes y agua. Con este smartwatch de Apple podrás controlar tu actividad física y mantenerte al tanto de tus llamadas y mensajes.",
    },
    { 
        id: "9" , 
        nombre: "POCO F3 EU 256GB Night Black", 
        marca: "Xiaomi", 
        stock: 80, 
        cantidad:1, 
        precio: 3599,  
        categoria: "Celular", 
        img: "https://i.ibb.co/RczGm4S/poco-f3-black.webp",
        imgs:{
            img2:"https://i.ibb.co/94B4Zfz/poco-f3-black-img2.webp",
            img3:"https://i.ibb.co/ynjX8NG/poco-f3-black-img3.webp",
            img4:"https://i.ibb.co/hKzZhDg/poco-f3-black-img4.webp",
        },
        description:"El POCO F3 se presenta como una de las mejores alternativas a los caros smartphones de gama alta. Para ello, este nuevo smartphone de Xiaomi añade un diseño totalmente renovado, aportando una sensación en mano “premium” y de tan solo 196 gramos."
    },
    { 
        id: "10", 
        nombre: "Mi 11 Lite 5G NE EU 256G Mint Green", 
        marca: "Xiaomi", 
        stock: 50, 
        cantidad:1, 
        precio: 1999,  
        categoria: "Celular", 
        img: "https://i.ibb.co/K7Dh9vN/mi-11-lite-5-G-mint-green.webp",
        imgs:{
            img2:"https://i.ibb.co/WfmvbmN/mi-11-lite-5-G-mint-green-img2.webp",
            img3:"https://i.ibb.co/dQ5NsJV/mi-11-lite-5-G-mint-green-img3.webp",
            img3:"https://i.ibb.co/MPBZj7z/mi-11-lite-5-G-mint-green-img4.webp",
            
        },
        description:"Ha vuelto a convocar un evento con novedades múltiples, ha vuelto a ampliar una familia y ha vuelto con la serie 11 Lite. Una línea de móviles que recoge el testigo de los primeros buques insignia de la marca cada año para añadir alguna novedad e intentar competir en relación calidad-precio en las gamas media y alta.Parte de esos estrenos es este nuevo Xiaomi 11 Lite 5G New Edition, que no sólo recuerda en nombre al Xiaomi Mi 11 Lite 5G, sino también en gran parte de sus características. Incluso ese diseño con el módulo cuadrado a modo de yin y yang. Un nuevo móvil de gama media con 5G y triple con coloridas opciones y pantalla FHD."
    },
    { 
        id: "11", 
        nombre: "Xiaomi 11T Pro US 8GB RAM 256GB ROM Meteorite Gray",   
        marca: "Xiaomi", 
        stock: 70, 
        cantidad:1, 
        precio: 3399,  
        categoria: "Celular", 
        img: "https://i.ibb.co/BKGQWf3/xiaomi-11t-pro-meteorite-gray.webp",
        imgs:{
            img2:"https://i.ibb.co/PYyZqTN/xiaomi-11t-pro-meteorite-gray-img2.webp", 
            img3:"https://i.ibb.co/JHbcHXy/xiaomi-11t-pro-meteorite-gray-img3.webp", 
            img4:"https://i.ibb.co/Pjfj2ww/xiaomi-11t-pro-meteorite-gray-img4.webp"
        },
        description:"El Xiaomi 11T Pro pone un pie en la tierra con el Snapdragon 888 al mando, acompañado de un procesador RAM de 8GB y 256GB de almacenamiento interno. El nuevo Xiaomi 11T Pro cuenta con una pantalla AMOLED de 6,67 pulgadas, refresco adaptativo (hasta a 120Hz) y resolución FullHD+, lo que nos deja 2.400 x 1.080 píxeles. La pantalla tiene un brillo máximo de 1.000 nits y un contraste de 5.000.000:1, además de ser compatible con contenidos HDR10+."
    
    },
    { 
        id: "12", 
        nombre: "Xiaomi 12 Purple 8GB RAM 256GB ROM",   
        marca: "Xiaomi", 
        stock: 40, 
        cantidad:1, 
        precio: 3599,  
        categoria: "Celular", 
        img: "https://i.ibb.co/dLfvL5r/xiaomi-12-purple.webp",
        imgs:{
            img2:"https://i.ibb.co/CvrFLGx/xiaomi-12-purple-img2.webp",  
            img3:"https://i.ibb.co/JRW6GVp/xiaomi-12-purple-img3.webp",
            img4:"https://i.ibb.co/6tYWp2G/xiaomi-12-purple-img4.webp",
        },
        description:"Gracias a nuestra constante búsqueda de la excelencia en la creación de lo que deseas, el Xiaomi 12 Pro está preparado para dominar cada escena con un conjunto de cámaras triples Pro de 50 MP, una pantalla WQHD+ dynamic de 120 Hz, el chipset Snapdragon® 8 Gen 1 más avanzado hasta la fecha y la carga inteligente Xiaomi HyperCharge de 120 W.",
    },
    { 
        id: "13", 
        nombre: "Galaxy S22+ 128GB Phantom Black",      
        marca: "Samsung",
        stock: 50, 
        cantidad:1, 
        precio: 4300,  
        categoria: "Celular",
        img: "https://i.ibb.co/B4y3s97/galaxy-s22-phantom-black-lite-gray.webp",
        imgs:{
            img2:"https://i.ibb.co/y8y2XY0/galaxy-s22-phantom-black-lite-gray-img2.webp",
            img3:"https://i.ibb.co/VBvGt19/galaxy-s22-phantom-black-lite-gray-img3.webp",
            img4:"https://i.ibb.co/G7dgSQ1/galaxy-s22-phantom-black-lite-gray-img4.webp",
        },
        description:"La vida no disminuye su ritmo y tomar un descanso para recargar energía es una vía rápida para la ansiedad de estar desconectado. La batería se adapta de manera inteligente a la forma en que usás tu smartphone, por lo que dura más de 24 horas.",
    },
    { 
        id: "14", 
        nombre: "Galaxy S22 Ultra 256GB Phantom Black", 
        marca: "Samsung",
        stock: 40, 
        cantidad:1, 
        precio: 5999,  
        categoria: "Celular", 
        img: "https://i.ibb.co/ySxJMCX/galaxy-s22-ultra-256-GB-phantom-black.webp",
        imgs:{
       
       
            img2:"https://i.ibb.co/fprfstW/galaxy-s22-ultra-256-GB-phantom-black-img2.webp",
            img3:"https://i.ibb.co/q9VBWSC/galaxy-s22-ultra-256-GB-phantom-black-img3.webp",
            img4:"https://i.ibb.co/8bHbGRb/galaxy-s22-ultra-256-GB-phantom-black-img4.webp",
        },
        description:"La IA mejorada toma 5000 mAh (típico) de potencia de un día al otro, adaptándose de manera inteligente a la forma en que usas tu smartphone. Para abreviar: ahorra energía para cuando más la necesitas, ya que ofrece una duración de la batería de más horas de las que hay en un día.",
    },
    { 
        id: "15", 
        nombre: `Televisor Samsung Smart TV 65" UHD 4K UN65AU7090GXPE`, 
        marca: "Samsung",
        stock: 40, 
        cantidad:1, 
        precio: 2199,  
        categoria: "Televisor", 
        img: "https://i.ibb.co/vDbPfsf/18891311-01.jpg",
        imgs:{
            img2:"https://i.ibb.co/XtSvVWt/18891311-02.jpg",
            img3:"https://i.ibb.co/ZTMY7SC/18891311-03.jpg",
            img4:"https://i.ibb.co/DKHjhWp/18891311-04.jpg",
        },
        description:"La mejora potente de 4K asegura que obtengas una resolución de hasta 4K para el contenido que te encanta. También, experimentarás expresiones de color más realistas gracias a su tecnología sofisticada de asignación de color.",
    },
    { 
        id: "16", 
        nombre: `Televisor Samsung Smart TV 50" QLED 4K QN50Q60BAGXPE (2022)`, 
        marca: "Samsung",
        stock: 30, 
        cantidad:1, 
        precio: 2299,  
        categoria: "Televisor", 
        img: "https://i.ibb.co/xMM7WhN/18911909-1.jpg",
        imgs:{
            img2:"https://i.ibb.co/RDhgmtb/18911909-2.jpg",
            img3:"https://i.ibb.co/QKYv2Cy/18911909-5.jpg",
            img4:"https://i.ibb.co/gPzMsym/18911909-6.jpg",
        },
        description:"Quantum HDR resalta el brillo y contraste para experimentes todo el poder en cada imagen. El mapeo de tono dinámico de HDR10+ supera últimos estándares y crea negros más profundos, una imagen más vibrante y detalles deslumbrantes.",
    },
    { 
        id: "17", 
        nombre: `TV CRYSTAL UHD 65 UN65BU8000GXPE`, 
        marca: "Samsung",
        stock: 20, 
        cantidad:1, 
        precio: 5299,  
        categoria: "Televisor", 
        img: "https://i.ibb.co/HqrD48k/19018094-1.jpg",
        imgs:{
            img2:"https://i.ibb.co/5rGW7zy/19018094-2.jpg",
            img3:"https://i.ibb.co/XyvFHQ0/19018094-3.jpg",
            img4:"https://i.ibb.co/2WBjYpp/19018094-4.jpg",
        },
        description:"Disfruta de un nivel diferente de UHD con tecnología de fósforo avanzada. Sumérgete en la imagen con mil millones de tonos de color. Dynamic Crystal Color ofrece variaciones realistas para que puedas ver cada detalle.",
    },
    { 
        id: "18", 
        nombre: `Televisor Xiaomi P1 50" Mi Android 10, 4K UHD, HDR10+`, 
        marca: "Xiaomi",
        stock: 40, 
        cantidad:1, 
        precio: 2399,  
        categoria: "Televisor", 
        img: "https://i.ibb.co/RD6TtG0/tv050xia06-1.webp",
        imgs:{
            img2:"https://i.ibb.co/xgZhs41/tv050xia06-2.webp",
            img3:"https://i.ibb.co/TYx9Cx3/tv050xia06-3.webp",
            img4:"https://i.ibb.co/xJnfNY2/tv050xia06-4.webp",
        },
        description:`Diseño sin biseles para una experiencia de visualización única
        Experimenta 4K Ultra HD en todo su esplendor
        Compatible con Dolby Vision® y HDR10+ para percibir más detalles tanto con luz como en la oscuridad
        Una gama de colores amplia que ofrece hasta un 94 % de cobertura de DCI-P3 combinada con una pantalla de 1070 millones de colores ofrece una calidad de imagen asombrosa y realista con colores vibrantes y detalles vivos.
        Suavizado de movimiento MEMC para una mayor fluidez sin trepidación
        Android TV, una forma más sencilla de disfrutar del entretenimiento que más te gusta
        Procesadores de cuatro núcleos para mayores posibilidades`,
    },
    { 
        id: "19", 
        nombre: `Televisor Xiaomi Q1 75" Mi QLED Android 10 4K UHD HDR10+`, 
        marca: "Xiaomi",
        stock: 25, 
        cantidad:1, 
        precio: 4299,  
        categoria: "Televisor", 
        img: "https://i.ibb.co/rwmd3jT/18659962-1.jpg",
        imgs:{
            img2:"https://i.ibb.co/QmZDMn6/18659962-2.jpg",
            img3:"https://i.ibb.co/YB80L6C/18659962-3.jpg",
            img4:"https://i.ibb.co/mSVgY3Z/18659962-4.jpg",
        },
        description:`La Mi TV Q1 75" puede mostrar 1.07 billones de colores, haciendo que cada tono sea preciso y puro, lo que resulta en transiciones más suaves.
        Bajo la pantalla, hay 384 LEDs en 192 zonas localizadas que pueden ajustar el brillo de forma independiente para mejorar el contraste de los colores. Esta tecnología hace que los elementos brillantes sean más brillantes y los oscuros más oscuros, mejorando en gran medida la claridad y la vivacidad de la imagen.
        Compatible con Dolby Vision y HDR10+, la pantalla QLED puede procesar y optimizar la calidad de la imagen fotograma a fotograma, mostrando claramente cada detalle brillante y oscuro con una calidad de imagen más cercana a la realidad.`,
    },
]